<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ReleaseNotes>
    </ReleaseNotes>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <!-- Version is automatically calculated by MinVer based on git tags -->
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <MinVerMinimumMajorMinor>1.1</MinVerMinimumMajorMinor>
  </PropertyGroup>
  <PropertyGroup>
    <Description>The core library that can used to create software architecture models.</Description>
    <Authors>Structurizr Limited</Authors>
    <Copyright>Copyright 2017-2023</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://structurizr.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/structurizr/dotnet</RepositoryUrl>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="MinVer" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>