<Project Sdk="Microsoft.NET.Sdk">

  <!-- Update this property group for every regular release -->
  <PropertyGroup>
    <ReleaseNotes></ReleaseNotes>
    <Version>1.1.1</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <Description>The API client for publishing C4 models to the Structurizr cloud service and on-premises installation.</Description>
    <Authors>StacyClouds</Authors>
    <Copyright>Copyright 2017-2026</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://c4sharp.net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/StacyClouds/c4sharp.net</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Structurizr.Core\Structurizr.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>