theme: jekyll-theme-cayman
title: C4Sharp.NET
description: C4 architecture modeling packages for .NET
url: https://c4sharp.com
baseurl: ""
show_downloads: false
markdown: kramdown

exclude:
  - api

defaults:
  - scope:
      path: ""
    values:
      layout: default
